name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: github.repository == 'trex-coe/trexio'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           submodules: true  

      - name: refresh apt
        run: sudo apt-get update

      - name: install dependencies
        run: sudo apt-get install emacs

      # this step is needed to pull the git submodule org-html-themes
      #- name: initialize submodules
      #  run: git submodule update --init

      - name: make
        run: cd tools/ && ./build_doc.sh && cd ..

      - name: pwd
        run: pwd

      - name: ls
        run: ls -sh ./docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
           branch: gh-pages
           folder: ./docs

#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./docs


